// Notifications store.
// Notifications are generated by real application events (interview started,
// resumed, paused, completed, ended, time expired, result generated) and
// persisted in localStorage so they survive refreshes.
//
// Deduplication: each notification carries a stable `key` (type + sessionId).
// The same event firing multiple times (re-renders, route changes, polling)
// only ever creates ONE notification.

import { useEffect, useState } from "react";

const STORAGE_KEY = "ia_notifications";
const LIMIT = 50;

const EVENT = "notifications-changed";

export const NOTIFICATION_TYPES = {
  STARTED: "interview.started",
  RESUMED: "interview.resumed",
  PAUSED: "interview.paused",
  COMPLETED: "interview.completed",
  ENDED: "interview.ended",
  EXPIRED: "interview.expired",
  RESULT: "interview.result",
};

function isStorageAvailable() {
  try {
    return typeof window !== "undefined" && !!window.localStorage;
  } catch {
    return false;
  }
}

function read() {
  if (!isStorageAvailable()) return [];
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    const items = raw ? JSON.parse(raw) : [];
    return Array.isArray(items) ? items : [];
  } catch {
    return [];
  }
}

function write(items) {
  if (isStorageAvailable()) {
    try {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
    } catch {
      /* storage full or unavailable — notifications stay in memory only */
    }
  }
  if (typeof window !== "undefined") {
    window.dispatchEvent(new CustomEvent(EVENT));
  }
}

function notifKey(type, sessionId) {
  return `${type}:${sessionId || "global"}`;
}

function makeId() {
  if (typeof crypto !== "undefined" && crypto.randomUUID) return crypto.randomUUID();
  return `n-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

export function getNotifications() {
  return read();
}

export function getUnreadCount() {
  return read().filter((n) => !n.read).length;
}

// Adds a notification unless an identical (type + session) one already exists.
export function addNotification({ type, sessionId, candidateId, candidateName, title, message }) {
  const key = notifKey(type, sessionId);
  const items = read();
  if (items.some((n) => n.key === key)) return;
  const item = {
    id: makeId(),
    key,
    type,
    sessionId: sessionId || null,
    candidateId: candidateId || null,
    candidateName: candidateName || null,
    title: title || type,
    message: message || "",
    createdAt: new Date().toISOString(),
    read: false,
  };
  write([item, ...items].slice(0, LIMIT));
}

export function markNotificationRead(id) {
  const items = read().map((n) => (n.id === id ? { ...n, read: true } : n));
  write(items);
}

export function markAllNotificationsRead() {
  const items = read().map((n) => ({ ...n, read: true }));
  write(items);
}

export function clearNotifications() {
  write([]);
}

// React hook that re-reads the store whenever it changes.
export function useNotifications() {
  const [items, setItems] = useState(() => read());

  useEffect(() => {
    const handler = () => setItems(read());
    window.addEventListener(EVENT, handler);
    return () => window.removeEventListener(EVENT, handler);
  }, []);

  return {
    items,
    unread: items.filter((n) => !n.read).length,
    markRead: markNotificationRead,
    markAllRead: markAllNotificationsRead,
    clear: clearNotifications,
  };
}
